[project]
name = "mcpserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=1.1.0",
    "mcp-use>=1.5.0",
    "mcp[cli]>=1.23.1",
    "streamlit>=1.52.0",
]
